img_size: 448
seed: 0

# dataset_name: ["mnist", ]
data_root: "path/HAM10k"
bb_dir: "path/Inception_V3"
json_root: ""
dataset_name: "HAM10k"
attribute_file_name: ""
derm7_folder: "/ocean/projects/asc170022p/shg121/PhD/ICLR-2022/data/Derm7pt"
derm7_meta: "meta.csv"
derm7_train_idx: "train_indexes.csv"
derm7_val_idx: "valid_indexes.csv"
C: [0.01]
n_samples: 50
model_name: "ham10000"

# model_arch: ["Resnet_10", "Resnet_18", Resnet_34, "AlexNet"]
model_arch: "Inception_V3"
pretrained: True
transfer_learning: False
batch_size: 32
lr: 0.001
logs: "path/Results"
bb_layers_for_concepts: [ "derma" ]
last_model_chk_pt_file: "best_val_prune_iteration_11_model_lt.pth.tar"
last_model_mask_file: "lt_mask_non_zero_params_31.5_ite_11.pkl"
num_classes: 2

# cav_flattening_type: ["max_pooled", "avg_pooled", "flattened"]
#cav_flattening_type: "flattened"
cav_flattening_type: "max_pooled"
#cav_flattening_type: "avg_pooled"

tcav_to_predict: {
  "Malignant": [
  # "Sex",
    "BWV", "RegularDG", "IrregularDG", "RegressionStructures",
    "IrregularStreaks", "RegularStreaks", "AtypicalPigmentNetwork", "TypicalPigmentNetwork"
]
}


continue_pruning: False
initialized_BB_weights: False
# g model configs:
hidden_features: 500
g_lr: 0.001
th: 0
val_after_th: 0
g_epoch: 5
# for max pooled
# g_chkpt: "best_epoch_16.pth.tar"

# for avg pooled
#g_chkpt: "best_epoch_19.pth.tar"

# for flattened
g_chkpt: "best_epoch_42.pth.tar"


# pruning configs
prune_type: "lt"
prune_iterations: 15
start_iter: 0

prune_percent: 10
topK: 3
# epoch for each of the pruned network
end_iter: 50
resample: False
epsilon: 0.0000006

concept_names: [
  # "Sex",
    "BWV", "RegularDG", "IrregularDG", "RegressionStructures",
    "IrregularStreaks", "RegularStreaks", "AtypicalPigmentNetwork", "TypicalPigmentNetwork"
]


labels: [ 'Benign', 'Malignant' ]
pcbm_lr: 0.01
pcbm_epoch: 35
pcbm_alpha: 0.00001
pcbm_l1_ratio: 0.99